name: zoo_tube_flutter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^0.13.1+1
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1
  go_router: ^3.0.1
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  miniplayer: ^1.0.0+2
  timeago: ^3.0.2
  curl_logger_dio_interceptor: ^0.0.2

  cupertino_icons: ^1.0.4
  flutter_native_splash: ^2.0.2
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/yt_logo_dark.png
#    - "assets/title_logo.svg"
#    - "assets/mail_icon.svg"
#    - "assets/uil_lock.svg"
#    - "assets/continue_with_apple.svg"
#    - "assets/google_color.svg"

#flutter_native_splash:
#  image: "assets/splash_image.png"
#  color: "#008CD6"
#
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/launch_icon.png"
#  adaptive_icon_foreground: "assets/android_launch_icon_foreground.png"
#  adaptive_icon_background: "assets/android_launch_icon_background.png"
#  © 2022 GitHub, Inc.
#  Terms
#  Privacy
#  Security
#  Status
#  Docs
#  Contact GitHub
#  Pricing
#  API
#  Training
#  Blog
#  About
#  Loading complete
